//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作权限检查.
        /// </summary>
        internal static string ACTION_AUTH_CHECK {
            get {
                return ResourceManager.GetString("ACTION_AUTH_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}点击.
        /// </summary>
        internal static string ACTION_BUTTON_CLICK {
            get {
                return ResourceManager.GetString("ACTION_BUTTON_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}处理.
        /// </summary>
        internal static string ACTION_DATA_SHOW {
            get {
                return ResourceManager.GetString("ACTION_DATA_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期表示.
        /// </summary>
        internal static string ACTION_LOAD {
            get {
                return ResourceManager.GetString("ACTION_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生数据访问错误。.
        /// </summary>
        internal static string ERROR_DATAACCESS {
            get {
                return ResourceManager.GetString("ERROR_DATAACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生逻辑判断错误。.
        /// </summary>
        internal static string ERROR_LOGIC {
            get {
                return ResourceManager.GetString("ERROR_LOGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发生页面访问错误。.
        /// </summary>
        internal static string ERROR_PAGE {
            get {
                return ResourceManager.GetString("ERROR_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已经保存到数据库。.
        /// </summary>
        internal static string IMSG0001 {
            get {
                return ResourceManager.GetString("IMSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [?].
        /// </summary>
        internal static string IMSG0002 {
            get {
                return ResourceManager.GetString("IMSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----/--/--.
        /// </summary>
        internal static string IMSG0003 {
            get {
                return ResourceManager.GetString("IMSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string IMSG0004 {
            get {
                return ResourceManager.GetString("IMSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string IMSG0005 {
            get {
                return ResourceManager.GetString("IMSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string IMSG0006 {
            get {
                return ResourceManager.GetString("IMSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ～.
        /// </summary>
        internal static string IMSG0007 {
            get {
                return ResourceManager.GetString("IMSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string IMSG0008 {
            get {
                return ResourceManager.GetString("IMSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFCC.
        /// </summary>
        internal static string IMSG0009 {
            get {
                return ResourceManager.GetString("IMSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string IMSG0010 {
            get {
                return ResourceManager.GetString("IMSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --:--:--.
        /// </summary>
        internal static string IMSG0011 {
            get {
                return ResourceManager.GetString("IMSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----/--/-- --:--:--.
        /// </summary>
        internal static string IMSG0012 {
            get {
                return ResourceManager.GetString("IMSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已添加成功。.
        /// </summary>
        internal static string IMSG0013 {
            get {
                return ResourceManager.GetString("IMSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string INFO_BUTTON_ADD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限设定.
        /// </summary>
        internal static string INFO_BUTTON_AUTHSET {
            get {
                return ResourceManager.GetString("INFO_BUTTON_AUTHSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量添加.
        /// </summary>
        internal static string INFO_BUTTON_BATCHNEWENTRY {
            get {
                return ResourceManager.GetString("INFO_BUTTON_BATCHNEWENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string INFO_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变更.
        /// </summary>
        internal static string INFO_BUTTON_CHANGE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        internal static string INFO_BUTTON_CLEAR {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string INFO_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string INFO_BUTTON_CONFIRM {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV FileDownload.
        /// </summary>
        internal static string INFO_BUTTON_CSVDOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_CSVDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string INFO_BUTTON_DELETE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 明细连接.
        /// </summary>
        internal static string INFO_BUTTON_DETAILLINK {
            get {
                return ResourceManager.GetString("INFO_BUTTON_DETAILLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string INFO_BUTTON_EDIT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件下载.
        /// </summary>
        internal static string INFO_BUTTON_FILEDOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_FILEDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据源形式下载(EXCEL).
        /// </summary>
        internal static string INFO_BUTTON_GRAPHDATADOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_GRAPHDATADOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片形式下载(PNG).
        /// </summary>
        internal static string INFO_BUTTON_GRAPHDOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_GRAPHDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格数据下载.
        /// </summary>
        internal static string INFO_BUTTON_GRIDDOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_GRIDDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string INFO_BUTTON_INSERT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string INFO_BUTTON_LOGIN {
            get {
                return ResourceManager.GetString("INFO_BUTTON_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件连接.
        /// </summary>
        internal static string INFO_BUTTON_MAILLINK {
            get {
                return ResourceManager.GetString("INFO_BUTTON_MAILLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息生成.
        /// </summary>
        internal static string INFO_BUTTON_MESSAGECREATE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_MESSAGECREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string INFO_BUTTON_NEWENTRY {
            get {
                return ResourceManager.GetString("INFO_BUTTON_NEWENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string INFO_BUTTON_OK {
            get {
                return ResourceManager.GetString("INFO_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        internal static string INFO_BUTTON_OUTPUT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分页.
        /// </summary>
        internal static string INFO_BUTTON_PAGGING {
            get {
                return ResourceManager.GetString("INFO_BUTTON_PAGGING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换到当前用户.
        /// </summary>
        internal static string INFO_BUTTON_REPLACEUSER {
            get {
                return ResourceManager.GetString("INFO_BUTTON_REPLACEUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报表生成.
        /// </summary>
        internal static string INFO_BUTTON_REPORTCREATE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_REPORTCREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报表下载.
        /// </summary>
        internal static string INFO_BUTTON_REPORTDOWNLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_REPORTDOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件上传.
        /// </summary>
        internal static string INFO_BUTTON_REPORTUPLOAD {
            get {
                return ResourceManager.GetString("INFO_BUTTON_REPORTUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        internal static string INFO_BUTTON_RETURN {
            get {
                return ResourceManager.GetString("INFO_BUTTON_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户角色清除.
        /// </summary>
        internal static string INFO_BUTTON_ROLE_CLEAR {
            get {
                return ResourceManager.GetString("INFO_BUTTON_ROLE_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户角色设定.
        /// </summary>
        internal static string INFO_BUTTON_ROLE_SET {
            get {
                return ResourceManager.GetString("INFO_BUTTON_ROLE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        internal static string INFO_BUTTON_SEARCH {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        internal static string INFO_BUTTON_SELECT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送.
        /// </summary>
        internal static string INFO_BUTTON_SEND {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设定.
        /// </summary>
        internal static string INFO_BUTTON_SET {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        internal static string INFO_BUTTON_SHOW {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示报表.
        /// </summary>
        internal static string INFO_BUTTON_SHOWREPORT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SHOWREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承认.
        /// </summary>
        internal static string INFO_BUTTON_SONIN {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SONIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        internal static string INFO_BUTTON_SORT {
            get {
                return ResourceManager.GetString("INFO_BUTTON_SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB切换.
        /// </summary>
        internal static string INFO_BUTTON_TABCHANGE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_TABCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string INFO_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("INFO_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次月.
        /// </summary>
        internal static string INFO_CANLENDAR_BUTTON_NEXT {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_BUTTON_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前月.
        /// </summary>
        internal static string INFO_CANLENDAR_BUTTON_PRE {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_BUTTON_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次年度.
        /// </summary>
        internal static string INFO_CANLENDAR_BUTTON_YEAR_NEXT {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_BUTTON_YEAR_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前年度.
        /// </summary>
        internal static string INFO_CANLENDAR_BUTTON_YEAR_PRE {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_BUTTON_YEAR_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_1 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_10 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_11 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_12 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_2 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_3 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_4 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_5 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_6 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_7 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_8 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9月.
        /// </summary>
        internal static string INFO_CANLENDAR_MONTH_9 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_MONTH_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_0 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_1 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_2 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_3 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_4 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_5 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六.
        /// </summary>
        internal static string INFO_CANLENDAR_WEEK_6 {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_WEEK_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        internal static string INFO_CANLENDAR_YEAR_SUBFIX {
            get {
                return ResourceManager.GetString("INFO_CANLENDAR_YEAR_SUBFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选.
        /// </summary>
        internal static string INFO_COMBOLIST_ALL {
            get {
                return ResourceManager.GetString("INFO_COMBOLIST_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前用户：.
        /// </summary>
        internal static string INFO_HEADER_LOGIN {
            get {
                return ResourceManager.GetString("INFO_HEADER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参照报表数据.
        /// </summary>
        internal static string INFO_PAGE_REPORTSHOW {
            get {
                return ResourceManager.GetString("INFO_PAGE_REPORTSHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理中....
        /// </summary>
        internal static string INFO_PROCCESSING {
            get {
                return ResourceManager.GetString("INFO_PROCCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有查询到数据。.
        /// </summary>
        internal static string INFO_SEARCH_NODATA {
            get {
                return ResourceManager.GetString("INFO_SEARCH_NODATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}行处理完成。.
        /// </summary>
        internal static string LMSG0001 {
            get {
                return ResourceManager.GetString("LMSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}正常结束。.
        /// </summary>
        internal static string LMSG0002 {
            get {
                return ResourceManager.GetString("LMSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}访问了{1}。.
        /// </summary>
        internal static string LMSG0003 {
            get {
                return ResourceManager.GetString("LMSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}按下了{1}。.
        /// </summary>
        internal static string LMSG0004 {
            get {
                return ResourceManager.GetString("LMSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}没有{1}访问权限。.
        /// </summary>
        internal static string LMSG0005 {
            get {
                return ResourceManager.GetString("LMSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储过程[{0}]被执行。返回值 : {1}.
        /// </summary>
        internal static string LMSG0006 {
            get {
                return ResourceManager.GetString("LMSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}没有{1}变更权限。.
        /// </summary>
        internal static string LMSG0007 {
            get {
                return ResourceManager.GetString("LMSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}session已过期。.
        /// </summary>
        internal static string LMSG0008 {
            get {
                return ResourceManager.GetString("LMSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 授权人1、2不能相同。.
        /// </summary>
        internal static string LMSG0009 {
            get {
                return ResourceManager.GetString("LMSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页.
        /// </summary>
        internal static string PAGING_PAGEUNITNAME {
            get {
                return ResourceManager.GetString("PAGING_PAGEUNITNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合计:.
        /// </summary>
        internal static string PAGING_SUMTITLE {
            get {
                return ResourceManager.GetString("PAGING_SUMTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最末.
        /// </summary>
        internal static string PAGING_TOOLTIP_END {
            get {
                return ResourceManager.GetString("PAGING_TOOLTIP_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次.
        /// </summary>
        internal static string PAGING_TOOLTIP_NEXT {
            get {
                return ResourceManager.GetString("PAGING_TOOLTIP_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前.
        /// </summary>
        internal static string PAGING_TOOLTIP_PREV {
            get {
                return ResourceManager.GetString("PAGING_TOOLTIP_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最初.
        /// </summary>
        internal static string PAGING_TOOLTIP_START {
            get {
                return ResourceManager.GetString("PAGING_TOOLTIP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 件.
        /// </summary>
        internal static string PAGING_UNITNAME {
            get {
                return ResourceManager.GetString("PAGING_UNITNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入{0}。.
        /// </summary>
        internal static string WMSG0001 {
            get {
                return ResourceManager.GetString("WMSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}和{1}不一致。.
        /// </summary>
        internal static string WMSG0002 {
            get {
                return ResourceManager.GetString("WMSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}需要包含{1}个字符的字幕・数字・符号三种文字。.
        /// </summary>
        internal static string WMSG0003 {
            get {
                return ResourceManager.GetString("WMSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要进行更新操作吗？.
        /// </summary>
        internal static string WMSG0004 {
            get {
                return ResourceManager.GetString("WMSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要进行删除操作吗？.
        /// </summary>
        internal static string WMSG0005 {
            get {
                return ResourceManager.GetString("WMSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要进行添加操作吗？.
        /// </summary>
        internal static string WMSG0006 {
            get {
                return ResourceManager.GetString("WMSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要进行取消操作吗？.
        /// </summary>
        internal static string WMSG0007 {
            get {
                return ResourceManager.GetString("WMSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已经存在。.
        /// </summary>
        internal static string WMSG0008 {
            get {
                return ResourceManager.GetString("WMSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}请输入{1}个以内的文字。.
        /// </summary>
        internal static string WMSG0009 {
            get {
                return ResourceManager.GetString("WMSG0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}请输入{1}个以内的字母或数字。.
        /// </summary>
        internal static string WMSG0010 {
            get {
                return ResourceManager.GetString("WMSG0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已经被其他用户更新，请刷新画面。.
        /// </summary>
        internal static string WMSG0011 {
            get {
                return ResourceManager.GetString("WMSG0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不存在。.
        /// </summary>
        internal static string WMSG0012 {
            get {
                return ResourceManager.GetString("WMSG0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的格式不正确。.
        /// </summary>
        internal static string WMSG0013 {
            get {
                return ResourceManager.GetString("WMSG0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的锁定已解除。.
        /// </summary>
        internal static string WMSG0014 {
            get {
                return ResourceManager.GetString("WMSG0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的密码再发行已成功。.
        /// </summary>
        internal static string WMSG0015 {
            get {
                return ResourceManager.GetString("WMSG0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择{0}。.
        /// </summary>
        internal static string WMSG0016 {
            get {
                return ResourceManager.GetString("WMSG0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请点击{0}。.
        /// </summary>
        internal static string WMSG0017 {
            get {
                return ResourceManager.GetString("WMSG0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统发生错误，无法进行删除。.
        /// </summary>
        internal static string WMSG0020 {
            get {
                return ResourceManager.GetString("WMSG0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的顺序关系不正确。.
        /// </summary>
        internal static string WMSG0021 {
            get {
                return ResourceManager.GetString("WMSG0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}行和第{1}行的顺序关系不正确。.
        /// </summary>
        internal static string WMSG0022 {
            get {
                return ResourceManager.GetString("WMSG0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不是有效日期。.
        /// </summary>
        internal static string WMSG0023 {
            get {
                return ResourceManager.GetString("WMSG0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}行的{1}不是有效日期。.
        /// </summary>
        internal static string WMSG0024 {
            get {
                return ResourceManager.GetString("WMSG0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择第{0}行的{1}。.
        /// </summary>
        internal static string WMSG0025 {
            get {
                return ResourceManager.GetString("WMSG0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在{0}中输入正确的整数。.
        /// </summary>
        internal static string WMSG0026 {
            get {
                return ResourceManager.GetString("WMSG0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入第{0}行的{1}。.
        /// </summary>
        internal static string WMSG0027 {
            get {
                return ResourceManager.GetString("WMSG0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要进行发信操作吗？.
        /// </summary>
        internal static string WMSG0028 {
            get {
                return ResourceManager.GetString("WMSG0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}被锁定。&lt;br/&gt;错误次数：{1}、最后访问日期：{2}.
        /// </summary>
        internal static string WMSG0029 {
            get {
                return ResourceManager.GetString("WMSG0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}的密码有效期限已过期。.
        /// </summary>
        internal static string WMSG0030 {
            get {
                return ResourceManager.GetString("WMSG0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入今天之前的日期。.
        /// </summary>
        internal static string WMSG0031 {
            get {
                return ResourceManager.GetString("WMSG0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}行的{1}中请输入今天之前的日期。.
        /// </summary>
        internal static string WMSG0033 {
            get {
                return ResourceManager.GetString("WMSG0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入的内容确认可以吗？.
        /// </summary>
        internal static string WMSG0035 {
            get {
                return ResourceManager.GetString("WMSG0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在{0}中请输入{1}位之内的整数。.
        /// </summary>
        internal static string WMSG0038 {
            get {
                return ResourceManager.GetString("WMSG0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入正确的开始日期和截至日期。.
        /// </summary>
        internal static string WMSG0039 {
            get {
                return ResourceManager.GetString("WMSG0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请添加到{0}中。.
        /// </summary>
        internal static string WMSG0040 {
            get {
                return ResourceManager.GetString("WMSG0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1})不存在，请选择别的数据。.
        /// </summary>
        internal static string WMSG0041 {
            get {
                return ResourceManager.GetString("WMSG0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要新生成？.
        /// </summary>
        internal static string WMSG0042 {
            get {
                return ResourceManager.GetString("WMSG0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}已经失败。.
        /// </summary>
        internal static string WMSG0043 {
            get {
                return ResourceManager.GetString("WMSG0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示只读权限的弹出窗口。.
        /// </summary>
        internal static string WMSG0044 {
            get {
                return ResourceManager.GetString("WMSG0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要舍弃修改的内容吗？.
        /// </summary>
        internal static string WMSG0046 {
            get {
                return ResourceManager.GetString("WMSG0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已超过添加可能件数的上限。.
        /// </summary>
        internal static string WMSG0047 {
            get {
                return ResourceManager.GetString("WMSG0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入值{0}中不能使用「&apos;」。.
        /// </summary>
        internal static string WMSG0048 {
            get {
                return ResourceManager.GetString("WMSG0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复的用户ID已经存在，不能进行添加。.
        /// </summary>
        internal static string WMSG0049 {
            get {
                return ResourceManager.GetString("WMSG0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中不能输入过去的日期。.
        /// </summary>
        internal static string WMSG0050 {
            get {
                return ResourceManager.GetString("WMSG0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ※因为分页过多，画面只显示开始的{0}页。.
        /// </summary>
        internal static string WMSG0051 {
            get {
                return ResourceManager.GetString("WMSG0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统登录失败，请再试一次。.
        /// </summary>
        internal static string WMSG0052 {
            get {
                return ResourceManager.GetString("WMSG0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件上传成功。.
        /// </summary>
        internal static string WMSG0053 {
            get {
                return ResourceManager.GetString("WMSG0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已超时。.
        /// </summary>
        internal static string WMSG0054 {
            get {
                return ResourceManager.GetString("WMSG0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只有只读权限，不能进行其他操作。.
        /// </summary>
        internal static string WMSG0060 {
            get {
                return ResourceManager.GetString("WMSG0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入{1}位以内的数字。.
        /// </summary>
        internal static string WMSG0061 {
            get {
                return ResourceManager.GetString("WMSG0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的文件不存在。.
        /// </summary>
        internal static string WMSG0064 {
            get {
                return ResourceManager.GetString("WMSG0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件上传失败。.
        /// </summary>
        internal static string WMSG0065 {
            get {
                return ResourceManager.GetString("WMSG0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能输入将来的日期。.
        /// </summary>
        internal static string WMSG0067 {
            get {
                return ResourceManager.GetString("WMSG0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能输入将来的日期（第{0}行）。.
        /// </summary>
        internal static string WMSG0068 {
            get {
                return ResourceManager.GetString("WMSG0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ０字节大小的文件不能上传。.
        /// </summary>
        internal static string WMSG0069 {
            get {
                return ResourceManager.GetString("WMSG0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名长度过长。.
        /// </summary>
        internal static string WMSG0070 {
            get {
                return ResourceManager.GetString("WMSG0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}中请输入{0}之后的日期。.
        /// </summary>
        internal static string WMSG0072 {
            get {
                return ResourceManager.GetString("WMSG0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入正确的邮件地址(XXX@XXX.XXX)。.
        /// </summary>
        internal static string WMSG0077 {
            get {
                return ResourceManager.GetString("WMSG0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入比{1}大的数字。.
        /// </summary>
        internal static string WMSG0080 {
            get {
                return ResourceManager.GetString("WMSG0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1})的用户信息不存在。.
        /// </summary>
        internal static string WMSG0081 {
            get {
                return ResourceManager.GetString("WMSG0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1})的邮件地址不能设定。.
        /// </summary>
        internal static string WMSG0082 {
            get {
                return ResourceManager.GetString("WMSG0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}中请输入正确的数字。.
        /// </summary>
        internal static string WMSG0083 {
            get {
                return ResourceManager.GetString("WMSG0083", resourceCulture);
            }
        }
    }
}
