//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMBConversionTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMBConversionTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error.
        /// </summary>
        internal static string GLOBAL_ERROR_CAP {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Error,Please check the log and contact the administrator!.
        /// </summary>
        internal static string GLOBAL_ERROR_TEXT {
            get {
                return ResourceManager.GetString("GLOBAL_ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string MSG_INFO_CAP {
            get {
                return ResourceManager.GetString("MSG_INFO_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果导出成功！.
        /// </summary>
        internal static string MSG_INFO_EXPORT_SUC {
            get {
                return ResourceManager.GetString("MSG_INFO_EXPORT_SUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状态更新成功！.
        /// </summary>
        internal static string MSG_INFO_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_INFO_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MSG_WARNING_CAP {
            get {
                return ResourceManager.GetString("MSG_WARNING_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前任务已经被他人领用！.
        /// </summary>
        internal static string MSG_WARNING_OTHER {
            get {
                return ResourceManager.GetString("MSG_WARNING_OTHER", resourceCulture);
            }
        }
    }
}
