IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[cmb_m_country]') AND type in (N'U'))
	DROP TABLE [dbo].[cmb_m_country];
GO

CREATE TABLE [dbo].[cmb_m_country](
	[coun_cd] [nvarchar](3) NOT NULL,
	[coun_num] [nvarchar](3) NOT NULL,
	[coun_name] [nvarchar](1000) NULL,
) 

GO

truncate table cmb_m_country;
insert into cmb_m_country values ('ALB','008',N'阿尔巴尼亚 Albania 阿尔马尼亚共和国 Republic of Albania');
insert into cmb_m_country values ('DZA','012',N'阿尔及利亚 Algeria 阿尔及利亚民主人民共和国 Democratic People''s Republic of Algeria');
insert into cmb_m_country values ('AFG','004',N'阿富汗 Afghanistan 阿富汗伊斯兰国 Islamic State of Afghanistan');
insert into cmb_m_country values ('ARG','032',N'阿根廷 Argentina 阿根廷共和国 Republic of Argentina');
insert into cmb_m_country values ('ARE','784',N'阿闻酋 United Arab Emirates 阿拉伯联合酋长国 United Arab Emirates');
insert into cmb_m_country values ('ABW','533',N'阿鲁巴 Aruba 阿鲁巴 Aruba');
insert into cmb_m_country values ('OMN','512',N'阿曼 Oman 阿曼苏丹国 Sultanate of Oman');
insert into cmb_m_country values ('AZE','031',N'阿塞拜疆 Azerbaijan 阿塞拜疆共和国 Republic of Azerbaijan');
insert into cmb_m_country values ('EGY','818',N'埃及 Egypt 阿拉伯埃及共和国 Arab Republic of Egypt');
insert into cmb_m_country values ('ETH','231',N'埃塞俄比亚 Ethiopia 埃塞俄比亚联邦民主共和国 Federal Democratic Republic of Ethiopia');
insert into cmb_m_country values ('IRL','372',N'爱尔兰 Ireland 爱尔兰 Ireland');
insert into cmb_m_country values ('EST','233',N'爱沙尼亚 Estonia 爱沙尼亚共和国 Republic of Estonia');
insert into cmb_m_country values ('AND','020',N'安道尔 Andorra 安道尔公国 Principality of Andorra');
insert into cmb_m_country values ('AGO','024',N'安哥拉 Angola 安哥拉共和国 Republic of Angola');
insert into cmb_m_country values ('AIA','660',N'安圭拉 Anguilla 安圭拉 Anguilla');
insert into cmb_m_country values ('ATG','028',N'安提瓜和巴布达 Antigua and Barbuda 安提瓜和巴布达 Antigua and Barbuda');
insert into cmb_m_country values ('AUT','040',N'奥地利 Austria 奥地利共和国 Republic of Austria');
insert into cmb_m_country values ('AUS','036',N'澳大利亚 Australia 澳大利亚联邦 Commonwealth of Australia');
insert into cmb_m_country values ('MAC','446',N'澳门 Macau 中国澳门特别行政区 Macau Special Administrative Region of China');
insert into cmb_m_country values ('BRB','052',N'巴巴多斯 Barbados 巴巴多斯 Barbados');
insert into cmb_m_country values ('PNG','598',N'巴布亚新几内亚 Papua New Guinea 巴布亚新几内亚独立国 Independent State of Papua New Guinea');
insert into cmb_m_country values ('BHS','044',N'巴哈马 Bahamas 巴哈马联邦 Commonwealth of the Bahamas');
insert into cmb_m_country values ('PAK','586',N'巴基斯坦 Pakistan 巴基斯坦伊斯兰共和国 Islamic Republic of Pakistan');
insert into cmb_m_country values ('PRY','600',N'巴拉圭 Paraguay 巴拉圭共和国 Republic of Paraguay');
insert into cmb_m_country values ('PSE','275',N'巴勒斯坦 Palestine 巴勒斯坦国 State of Palestine');
insert into cmb_m_country values ('BHR','048',N'巴林 Bahrain 巴林国 State of Bahrain');
insert into cmb_m_country values ('PAN','591',N'巴拿马 Panama 巴拿马共和国 Republic of Panama');
insert into cmb_m_country values ('BRA','076',N'巴西 Brazil 巴西联邦共和国 Federative Republic of Brazil');
insert into cmb_m_country values ('BLR','112',N'白俄罗斯 Belarus 白俄罗斯共和国 Republic of Belarus');
insert into cmb_m_country values ('BMU','060',N'百慕大 Bermuda 百慕大群岛 Bermuda Islands');
insert into cmb_m_country values ('BGR','100',N'保加利亚 Bulgaria 保加利亚共和国 Republic ov Bulgaria');
insert into cmb_m_country values ('MNP','580',N'北马里亚纳 Northern Marianas 北马里亚纳自由联邦 Commonwealth of the Northern Marianas');
insert into cmb_m_country values ('PLW','585',N'帕劳 Palau 帕劳共和国 Republic of Palau');
insert into cmb_m_country values ('BEN','204',N'贝宁 Benin 贝宁共和国 Republic of Benin');
insert into cmb_m_country values ('BEL','056',N'比利时 Belgium 比利时王国 Kingdom of belgium');
insert into cmb_m_country values ('ISL','352',N'冰岛 Iceland 冰岛共和国 Republic of Iceland');
insert into cmb_m_country values ('PRI','630',N'波多黎各 Puerto Rico 波多黎各自由联邦 Commonwealth of Puerto Rico');
insert into cmb_m_country values ('POL','616',N'波兰 Poland 波兰共和国 Republic of Poland');
insert into cmb_m_country values ('BOL','068',N'玻利维亚 Bolivia 玻利维亚共和国 Republic of Bolivia');
insert into cmb_m_country values ('BIH','070',N'波斯尼亚和黑塞哥维那 Bosnia and Herzegovina 波斯尼亚和黑塞哥维那共和国 Republic of Bosnia and Herzegovina');
insert into cmb_m_country values ('BWA','072',N'博茨瓦纳 Botswana 博茨瓦纳共和国 Republic of Botswana');
insert into cmb_m_country values ('BLZ','084',N'伯利兹 Belize 伯利兹 Belize');
insert into cmb_m_country values ('BTN','064',N'不丹 Bhutan 不丹王国 Kingdom of Bhutan');
insert into cmb_m_country values ('BFA','854',N'布基纳法索 Burkina Faso 布基纳法索 Burkina Faso');
insert into cmb_m_country values ('BDI','108',N'布隆迪 Burundi 布隆迪共和国 Republic of Burundi');
insert into cmb_m_country values ('BVT','074',N'布维岛 Bouvet Island 布维岛 Bouvet Island');
insert into cmb_m_country values ('PRK','408',N'朝鲜 Korea,Democratic People''s Republic of 朝鲜民主主义人民共和国 Democratic People''s Republic of Ko-rea');
insert into cmb_m_country values ('GNQ','226',N'赤道几内亚 Equatorial Guinea 赤道几内亚共和国 Republic of Equatorial Guinea');
insert into cmb_m_country values ('DNK','208',N'丹麦 Denmark 丹麦王国 Kingdom of Denmark');
insert into cmb_m_country values ('DEU','276',N'德国 Germany 德意志联邦共和国 Federal Republic of Germany');
insert into cmb_m_country values ('TMP','626',N'东帝汶 East Timor 东帝汶 East Timor');
insert into cmb_m_country values ('TGO','768',N'多哥 Togo 多哥共和国 Republic of Tago');
insert into cmb_m_country values ('DOM','214',N'多米尼加共和国 Dominican Republic 多米尼加共和国 Dominican Republic');
insert into cmb_m_country values ('DMA','212',N'多米尼克 Dominica 多米尼克国 Commonwealth of Dominica');
insert into cmb_m_country values ('RUS','643',N'俄罗斯联邦 Russia Federation 俄罗斯联邦 Russian Federation');
insert into cmb_m_country values ('ECU','218',N'厄瓜多尔 Ecuador 厄瓜多尔共和国 Republic of Ecuador');
insert into cmb_m_country values ('ERI','232',N'厄立特里亚 Eritrea 厄立特里亚国 State of Eritrea');
insert into cmb_m_country values ('FRA','250',N'法国 France 法兰西共和国 French Republic');
insert into cmb_m_country values ('FRO','234',N'法罗群岛 Faroe Islands 法罗群岛 Faroe Islands');
insert into cmb_m_country values ('PYF','258',N'法属波利尼西亚 French Polynesia 法属波利尼西亚 French Polynesia');
insert into cmb_m_country values ('GUF','254',N'法属圭亚那 French Guiana 法属圭亚那 French Guiana');
insert into cmb_m_country values ('ATF','260',N'法属南部领土 French Southern Territo-ries 法属南部领土 French Southern Territories');
insert into cmb_m_country values ('VAT','336',N'梵蒂冈 Vatican 梵蒂冈城国 Vatican City State');
insert into cmb_m_country values ('PHL','608',N'菲律宾 Philippines 菲律宾共和国 Republic of the Philippines');
insert into cmb_m_country values ('FJI','242',N'斐济 Fiji 斐济群岛共和国 Republic of Fiji Islands');
insert into cmb_m_country values ('FIN','246',N'芬兰 Finland 芬兰共和国 Republic of Finland');
insert into cmb_m_country values ('CPV','132',N'佛得角 Cape Verde 佛得角共和国 Republic of Cape Verde');
insert into cmb_m_country values ('GMB','270',N'冈比亚Gambia 冈比亚共和国 Republic of Gambia');
insert into cmb_m_country values ('COD','180',N'刚果（金）Congo,the Democratic Republic of the 刚果民主共和国Democratic Republic of Congo');
insert into cmb_m_country values ('COG','178',N'刚果（布） Congo 刚果共和国 Republic of Congo');
insert into cmb_m_country values ('COL','170',N'哥伦比亚 Colombia 哥伦比亚共和国 Republic of Colombia');
insert into cmb_m_country values ('CRI','188',N'哥斯达黎加 Costa Rica 哥斯达黎加共和国 Republic of Costa Rica');
insert into cmb_m_country values ('GRD','308',N'格林纳达 Grenada 格林纳达 Grenada');
insert into cmb_m_country values ('GRL','304',N'格陵兰 Greenland 格陵兰 Greenland');
insert into cmb_m_country values ('GEO','268',N'格鲁吉亚 Georgia 格鲁吉亚Georgia');
insert into cmb_m_country values ('CUB','192',N'古巴 Cuba 古巴共和国 Republic of Cuba');
insert into cmb_m_country values ('GLP','312',N'瓜德罗普 Guadeloupe 瓜德罗普 Guadeloupe');
insert into cmb_m_country values ('GUM','316',N'关岛 Guam 关岛 Guam');
insert into cmb_m_country values ('GUY','328',N'圭亚那 Guyana 圭亚那合作共和国 Cooperative Republic of Guyana');
insert into cmb_m_country values ('KAZ','398',N'哈萨克斯坦 Kazakhstan 哈萨克斯坦共和国 Republic of Kazakhstan');
insert into cmb_m_country values ('HTI','332',N'海地 Haiti 海地共和国 Republic of Haiti');
insert into cmb_m_country values ('KOR','410',N'韩国 Korea,Republic of 大韩民国 Republic of Korea');
insert into cmb_m_country values ('NLD','528',N'荷兰 Netherlands 荷兰王国 Kingdom of the Netherlands');
insert into cmb_m_country values ('ANT','530',N'荷属安的列斯 Netherlands Antilles 荷属安的列斯 Netherlands Antilles');
insert into cmb_m_country values ('HMD','334',N'赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands 赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands');
insert into cmb_m_country values ('HND','340',N'洪都拉斯 Honduras 洪都拉斯共和国 Republic of honduras');
insert into cmb_m_country values ('KIR','296',N'基里巴斯 Kiribati 基里巴斯共和国 Republic of Kiribati');
insert into cmb_m_country values ('DJI','262',N'吉布提 Djibouti 吉布提共和国 Republic of Djibouti');
insert into cmb_m_country values ('KGZ','417',N'吉尔吉斯斯坦 Kyrgyzstan 吉尔吉斯共和国 Kyrgyz Republic');
insert into cmb_m_country values ('GIN','324',N'几内亚 Guinea 几内亚共和国 Republic of Guinea');
insert into cmb_m_country values ('GNB','624',N'几内亚比绍 Guine-bissau 几内亚比绍共和国 Republic of Guine-bissau');
insert into cmb_m_country values ('CAN','124',N'加拿大 Canada 加拿大 Canada');
insert into cmb_m_country values ('GHA','288',N'加纳 Ghana 加纳共和国 Republic of Ghana');
insert into cmb_m_country values ('GAB','266',N'加蓬 Gabon 加蓬共和国 Gabonese Republic');
insert into cmb_m_country values ('KHM','116',N'柬埔寨 Cambodia 柬埔寨王国 Kingdom of Cambodia');
insert into cmb_m_country values ('CZE','203',N'捷克 Czech Repoublic 捷克共和国 Czech Republic');
insert into cmb_m_country values ('ZWE','716',N'津巴布韦 Zimbabwe 津巴布韦共和国 Republic of Zimbabwe');
insert into cmb_m_country values ('CMR','120',N'喀麦隆 Cameroon 喀麦隆共和国 Republic of Cameroon');
insert into cmb_m_country values ('QAT','634',N'卡塔尔 Qatar 卡塔尔国 State of Qatar');
insert into cmb_m_country values ('CYM','136',N'开曼群岛 Cayman Islands 开曼群岛 Cayman Islands');
insert into cmb_m_country values ('CCK','166',N'科科斯(基林)群岛 Cocos(Keeling) Islands 科科斯(基林)群岛 Cocos(Keeling) Islands');
insert into cmb_m_country values ('COM','174',N'科摩罗 Comoros 科摩罗伊斯兰联邦共和国 Federal Islamic Republic of the Co-moros');
insert into cmb_m_country values ('CIV','384',N'科特迪瓦 Cote d''Ivoire 科特迪瓦共和国 Republic of Cote d''Ivire');
insert into cmb_m_country values ('KWT','414',N'科威特 Kuwait 科威特国 State of Kuwait');
insert into cmb_m_country values ('HRV','191',N'克罗地亚 Croatia 克罗地亚共和国 Republic of Croatia');
insert into cmb_m_country values ('KEN','404',N'肯尼亚 Kenya 肯尼亚共和国 Republic of Kenya');
insert into cmb_m_country values ('COK','184',N'库克群岛 Cook Islands 库克群岛 Cook Islands');
insert into cmb_m_country values ('LVA','428',N'拉脱维亚 Latvia 拉脱维亚共和国 Republic of Latvia');
insert into cmb_m_country values ('LSO','426',N'莱索托 Lesotho 莱索托王国 Kingdom of Lesoto');
insert into cmb_m_country values ('LAO','418',N'老挝 Lao 老挝人民民主共和国 Lao People''s Democratic Republic');
insert into cmb_m_country values ('LBN','422',N'黎巴嫩 Lebanon 黎巴嫩共和国 Republic of Lebanon');
insert into cmb_m_country values ('LBR','430',N'利比里亚 Liberia 利比里亚共和国 Republic of Liberia');
insert into cmb_m_country values ('LBY','434',N'利比亚 Libya 大阿拉伯利比亚人民社会主义民众国 Great Socialist People''s Libyan Arab jamahiriya');
insert into cmb_m_country values ('LTU','440',N'立陶宛 Lithuania 立陶宛共和国 Republic of Lithuania');
insert into cmb_m_country values ('LIE','438',N'列支敦士登 Liechtenstein 列支敦士登公国 Principality of Liechtenstein');
insert into cmb_m_country values ('REU','638',N'留尼汪 Reunion 留尼汪 Reunion');
insert into cmb_m_country values ('LUX','442',N'卢森堡 Luxembourg 卢森堡大公国 Grand Duchy of Luxembourg');
insert into cmb_m_country values ('RWA','646',N'卢旺达 Rwanda 卢旺达共和国 Republic of Rwanda');
insert into cmb_m_country values ('ROM','642',N'罗马尼亚 Romania 罗马尼亚 Romania');
insert into cmb_m_country values ('MDG','450',N'马达加斯加 Madagascar 马达加斯加共和国 Republic of Madagascar');
insert into cmb_m_country values ('MLT','470',N'马耳他 Malta 马耳他共和国 Republic of Malta');
insert into cmb_m_country values ('MDV','462',N'马尔代夫 Maldives 马尔代夫共和国 Republic of maldives');
insert into cmb_m_country values ('FLK','238',N'福克兰群岛（马尔维纳斯群岛） Falkland Islands ( Malvinas) 福克兰群岛 (马尔维纳斯群岛)Falkland Islands ( Malvinas)');
insert into cmb_m_country values ('MWI','454',N'马拉维 Malawi 马拉维共和国 Republic of Malawi');
insert into cmb_m_country values ('MYS','458',N'马来西亚 Malaysia 马来西亚 Malaysia');
insert into cmb_m_country values ('MLI','466',N'马里 Mali 马里共和国 Republic of Mali');
insert into cmb_m_country values ('MKD','807',N'前南马其顿 MACEDONIA,THE FORMER YUGOSLAV REPUBLIC OF 前南斯拉夫马其顿共和国 The former Yugoslav Republic of Macedonia');
insert into cmb_m_country values ('MHL','584',N'马绍尔群岛 Marshall Islands 马绍尔群岛共和国 Republic of the marshall Islands');
insert into cmb_m_country values ('MTQ','474',N'马提尼克 Martinique 马提尼克 Martinique');
insert into cmb_m_country values ('MYT','175',N'马约特 Mayotte 马约特 Mayotte');
insert into cmb_m_country values ('MUS','480',N'毛里求斯 Mauritius 毛里求斯共和国 Republic of Mauritius');
insert into cmb_m_country values ('MRT','478',N'毛里塔尼亚 Mauritania 毛里塔尼亚伊斯兰共和国 Islamic Republic of Mauritania');
insert into cmb_m_country values ('USA','840',N'美国 United States 美利坚合众国 United States of America');
insert into cmb_m_country values ('ASM','016',N'美属萨摩亚 American Samoa 美属萨摩亚 American Samoa');
insert into cmb_m_country values ('UMI','581',N'美国本土外小岛屿 United States Minor Outlying Islands 美国本土外小岛屿 United States Minor Outlying Islands');
insert into cmb_m_country values ('VIR','850',N'美属维尔京群岛 United States Virgin Is-lands 美属维尔京群岛 United States Virgin Islands');
insert into cmb_m_country values ('MNG','496',N'蒙古 Mongolia 蒙古国 Mongolia');
insert into cmb_m_country values ('MSR','500',N'蒙特塞拉特 Montserrat 蒙特塞拉特 Montserrat');
insert into cmb_m_country values ('BGD','050',N'孟加拉国 Bangladesh 孟加拉人民共和国 People''s Republic of Bangladesh');
insert into cmb_m_country values ('PER','604',N'秘鲁 Peru 秘鲁共和国 Republic of Peru');
insert into cmb_m_country values ('FSM','583',N'密克罗尼西亚联邦 Micronesia，Federated states of 密克罗尼西亚联邦 Federated States of Micronesia');
insert into cmb_m_country values ('MMR','104',N'缅甸 Myanmar 缅甸联邦 Union of Myanmar');
insert into cmb_m_country values ('MDA','498',N'摩尔多瓦 Moldova 摩尔多瓦共和国 Republic of Moldova');
insert into cmb_m_country values ('MAR','504',N'摩洛哥 Morocco 摩洛哥王国 Kingdom of Morocco');
insert into cmb_m_country values ('MCO','492',N'摩纳哥 Monaco 摩纳哥公国 Principality of Monaco');
insert into cmb_m_country values ('MOZ','508',N'莫桑比克 Mozambique 莫桑比克共和国 Republic of Mozambique');
insert into cmb_m_country values ('MEX','484',N'墨西哥 Mexico 墨西哥合众国 United States of Mexico');
insert into cmb_m_country values ('NAM','516',N'纳米比亚 Namibia 纳米比亚共和国 Republic of Namibia');
insert into cmb_m_country values ('ZAF','710',N'南非 South Africa 南非共和国 Republic of South Africa');
insert into cmb_m_country values ('ATA','010',N'南极洲 Antarctica 南极洲 Antarctica');
insert into cmb_m_country values ('SGS','239',N'南乔治亚岛和南桑德韦奇岛 South Georgia and South Sandwich Islands 南乔治亚岛和南桑德韦奇岛 South Georgia and South Sandwich Islands');
insert into cmb_m_country values ('NRU','520',N'瑙鲁 Nauru 瑙鲁共和国 Republic of Nauru');
insert into cmb_m_country values ('NPL','524',N'尼泊尔 Nepal 尼泊尔王国 Kingdom of Nepal');
insert into cmb_m_country values ('NIC','558',N'尼加拉瓜 Nicaragua 尼加拉瓜共和国 Republic of Nicaragua');
insert into cmb_m_country values ('NER','562',N'尼日尔 Niger 尼日尔共和国 Republic of Niger');
insert into cmb_m_country values ('NGA','566',N'尼日利亚 Nigeria 尼日利亚联邦共和国 Federal Republic of Nigeria');
insert into cmb_m_country values ('NIU','570',N'纽埃 Niue 纽埃 Niue');
insert into cmb_m_country values ('NOR','578',N'挪威 Norway 挪威王国 Kingdom of Norway');
insert into cmb_m_country values ('NFK','574',N'诺福克岛 Norfolk Island 诺福克岛 Norfolk Island');
insert into cmb_m_country values ('PCN','612',N'皮特凯恩 Pitcairn 皮竺凯恩 Pitcairn');
insert into cmb_m_country values ('PRT','620',N'葡萄牙 Portugal 葡萄牙共和国 Pirtuguese Republic');
insert into cmb_m_country values ('JPN','392',N'日本 Japan 日本国 Japan');
insert into cmb_m_country values ('SWE','752',N'瑞典 Sweden 瑞典王国 Kingdom of Sweden');
insert into cmb_m_country values ('CHE','756',N'瑞士 Switzerland 瑞士联邦 Swiss Confederation');
insert into cmb_m_country values ('SLV','222',N'萨尔瓦多 El Salvador 萨尔瓦多共和国 Republic of El Salvador');
insert into cmb_m_country values ('SLE','694',N'塞拉利昂 Sierra leone 塞拉利昂共和国 Republic of Sierra Leone');
insert into cmb_m_country values ('SEN','686',N'塞内加尔 Senegal 塞内加尔共和国 Republic of Senegal');
insert into cmb_m_country values ('CYP','196',N'塞浦路斯 Cyprus 塞浦路斯共和国 Republic of Cyprus');
insert into cmb_m_country values ('SYC','690',N'塞舌尔 Seychells 塞舌尔共和国 Republic of Seychelles');
insert into cmb_m_country values ('SAU','682',N'沙竺阿拉伯 Saudi Arabia 沙特阿拉伯王国 Kingdom of Saudi Arabia');
insert into cmb_m_country values ('CXR','162',N'圣诞岛 Christmas Island 圣诞岛 Christmas Island');
insert into cmb_m_country values ('STP','678',N'圣多美和普林西比 Sao Tome and Principe 圣多美和普林西比民主共和国 Democratic Republic of Sao Tome and Principe');
insert into cmb_m_country values ('SHN','654',N'圣赫勒拿 Saint helena 圣赫勒拿 Saint Helena');
insert into cmb_m_country values ('KNA','659',N'圣基茨和尼维斯 Saint Kitts and nevis 圣革茨和尼维斯联邦 Federation of Saint Kitts and nevis');
insert into cmb_m_country values ('LCA','662',N'圣卢西亚 Saint lucia 圣卢西亚 Saint Lucia');
insert into cmb_m_country values ('SMR','674',N'圣马力诺 San Marion 圣马力诺共和国 Republic of San Marino');
insert into cmb_m_country values ('SPM','666',N'圣皮埃尔和密克隆 Saint Pierre and Miquelon 圣皮埃尔和密克隆 Saint Pierre and Miquelon');
insert into cmb_m_country values ('VCT','670',N'圣文森特和格林纳丁斯 Saint Vincent and the Grenadines 圣文森特和格林纳丁斯 Saint Vincent and the Grenadines');
insert into cmb_m_country values ('LKA','144',N'斯里兰卡 Sri Lanka 斯里兰卡民主社会主义共和国 Democratic Socialist Republic of Srilanka');
insert into cmb_m_country values ('SVK','703',N'斯洛伐克 Slovakia 斯洛伐克共和国 Slovak Republic');
insert into cmb_m_country values ('SVN','705',N'斯洛文尼亚 Slovenia 斯洛文尼亚共和国 Republic of Slovenia');
insert into cmb_m_country values ('SJM','744',N'斯瓦尔巴岛和扬马延岛 Svalbard and jan Mayen Islands 斯瓦尔巴岛和扬马延岛 Svalbard and Jan mayen islands');
insert into cmb_m_country values ('SWZ','748',N'斯威士兰 Swaziland 斯威士兰王国 Kingdom of Swaziland');
insert into cmb_m_country values ('SDN','736',N'苏丹 Sudan 苏丹共和国 Republic of the Sudan');
insert into cmb_m_country values ('SUR','740',N'苏里南 Suriname 苏里南共和国 Republic of Suriname');
insert into cmb_m_country values ('SOM','706',N'索马里 Somalia 索马里共和国 Somali Republic');
insert into cmb_m_country values ('SLB','090',N'所罗门群岛 Solomon Islands 所罗门群岛 Solomon Islands');
insert into cmb_m_country values ('TJK','762',N'塔吉克斯坦 Tajikistan 塔吉克斯坦共和国 Republic of Tajikistan');
insert into cmb_m_country values ('THA','764',N'泰国 Thailand 泰王国 Kingdom of Thailand');
insert into cmb_m_country values ('TZA','834',N'坦桑尼亚 Tanzania 坦桑尼亚联合共和国 United Republic of Tanzania');
insert into cmb_m_country values ('TON','776',N'汤加 Tonga 汤加王国 Kingdom of Tonga');
insert into cmb_m_country values ('TCA','796',N'特克斯科斯群岛 Turks and Caicos Islands 特克斯和凯科斯群岛 Turks and Caicos Islands');
insert into cmb_m_country values ('TTO','780',N'特立尼达和多巴哥 Trinidad and Tobago 特立尼达和多巴哥共和国 Republic of Trinidad and Tobago');
insert into cmb_m_country values ('TUN','788',N'突尼斯 Tunisia 突尼斯共和国 Republic of Tunisia');
insert into cmb_m_country values ('TUV','798',N'图瓦卢 Tuvalu 图瓦卢 Tuvalu');
insert into cmb_m_country values ('TUR','792',N'土耳其 Turkey 土耳其共和国 Republic of Turkey');
insert into cmb_m_country values ('TKM','795',N'土库曼斯坦 Turkmenistan 土库曼斯坦 Turkmenistan');
insert into cmb_m_country values ('TKL','772',N'托克劳 Tokelau 托克劳 Tokelau');
insert into cmb_m_country values ('WLF','876',N'瓦利斯和富图纳 Wallis and Futuna 瓦利斯和富图纳 Wallis and Futuna');
insert into cmb_m_country values ('VUT','548',N'瓦努阿图 Vanuatu 瓦努阿图共和国 Republic of Vanuatu');
insert into cmb_m_country values ('GTM','320',N'危地马拉 Guatemala 危地马拉共和国 Republic of Guatemala');
insert into cmb_m_country values ('VEN','862',N'委内瑞拉 Venezuela 委内瑞拉共和国 Republic of Venezuela');
insert into cmb_m_country values ('BRN','096',N'文莱 Brunei Darussalam 文莱达鲁萨兰国 Brunei Darussalam');
insert into cmb_m_country values ('UGA','800',N'乌干达 Uganda 乌干达共和国 Republic of Uganda');
insert into cmb_m_country values ('UKR','804',N'乌克兰 Ukraine 乌克兰 Ukraine');
insert into cmb_m_country values ('URY','858',N'乌拉圭 Uruguay 乌拉圭东岸共和国 Oriental Republic of Uruguay');
insert into cmb_m_country values ('UZB','860',N'乌兹别克斯坦 Uzbekistan 乌兹别克斯坦共和国 Republic of Uzbekistan');
insert into cmb_m_country values ('ESP','724',N'西班牙 Spain 西班牙 Spain');
insert into cmb_m_country values ('ESH','732',N'西撒哈拉 Western Sahara 西撒哈拉 Western Sahara');
insert into cmb_m_country values ('WSM','882',N'萨摩亚 Samoa 萨摩亚独立国 Independent State of Samoa');
insert into cmb_m_country values ('GRC','300',N'希腊 Greece 希腊共和国 Hellenic Republic');
insert into cmb_m_country values ('HKG','344',N'香港 Hong Kong 中国香港特别行政区 Hong Kong Special Administrative Region of China');
insert into cmb_m_country values ('SGP','702',N'新加坡 Singapore 新加坡共和国 Republic of Singapore');
insert into cmb_m_country values ('NCL','540',N'新喀里多尼亚 New Caledonia 新喀里多尼亚 New Caledonia');
insert into cmb_m_country values ('NZL','554',N'新西兰 New Zealand 新西兰 New Zealand');
insert into cmb_m_country values ('HUN','348',N'匈牙利 Hungary 匈牙利共和国 Republic of Hungary');
insert into cmb_m_country values ('SYR','760',N'叙利亚 Syria 阿拉伯叙利亚共和国 Syrian Arab Republic');
insert into cmb_m_country values ('JAM','388',N'牙买加 Jamaica 牙买加 Jamaica');
insert into cmb_m_country values ('ARM','051',N'亚美尼亚 Armenia 亚美尼亚共和国 Republic of Armenia');
insert into cmb_m_country values ('YEM','887',N'也门 Yemen 也门共和国 Republic of Yemen');
insert into cmb_m_country values ('IRQ','368',N'伊拉克 Iraq 伊拉克共和国 Republic of Iraq');
insert into cmb_m_country values ('IRN','364',N'伊朗 Iran 伊朗伊斯兰共和国 Islamic Rupublic of Iran');
insert into cmb_m_country values ('ISR','376',N'以色列 Israel 以色列国 State of Israel');
insert into cmb_m_country values ('ITA','380',N'意大利 Italy 意大利共和国 Republic of Italy');
insert into cmb_m_country values ('IND','356',N'印度 India 印度共和国 Republic of India');
insert into cmb_m_country values ('IDN','360',N'印度尼西亚 Indonesia 印度尼西亚共和国 Republic of Indonesia');
insert into cmb_m_country values ('GBR','826',N'英国 United Kingdom 大不列颠及北爱尔兰联合王国 United Kingdom of Great Britain and Northern ireland');
insert into cmb_m_country values ('VGB','092',N'英属维尔京群岛 British Virgin Islands 英属维尔京群岛 British Virgin Islands');
insert into cmb_m_country values ('IOT','086',N'英属印度洋领地 British indian Ocean Territory 英属印度洋领地 British Indian Ocean Territory');
insert into cmb_m_country values ('JOR','400',N'约旦 Jordan 约旦哈希姆王国 Hashemite Kingdom of Jordan');
insert into cmb_m_country values ('VNM','704',N'越南 Viet Nam 越南社会主义共和国 Socialist Republic of Viet Nam');
insert into cmb_m_country values ('ZMB','894',N'赞比亚 Zambia 赞比亚共和国 Republic of Zambia');
insert into cmb_m_country values ('TCD','148',N'乍得 Chad 乍得共和国 Republic of Chad');
insert into cmb_m_country values ('GIB','292',N'直布罗陀 Gibraltar 直布罗陀 Gibraltar');
insert into cmb_m_country values ('CHL','152',N'智利 Chile 智利共和国 Republic of Chile');
insert into cmb_m_country values ('CAF','140',N'中非 Central Africa 中非共和国 Central African Republic');
insert into cmb_m_country values ('CHN','156',N'中国 China 中华人民共和国 People''s Republic of China');
insert into cmb_m_country values ('TWN','158',N'中国台湾 Taiwan,China 中国台湾 Chinese Taiwan');
insert into cmb_m_country values ('SRB','688',N'塞尔维亚 SERBIA 塞尔维亚共和国 Republic of SERBIA');
insert into cmb_m_country values ('MNE','499',N'黑山 MONTENEGRO 黑山共和国 Republic of MONTENEGRO');

